[versions]
activityCompose = "1.10.1"
androidImageCropper = "4.6.0"
annotation = "1.9.1"
appcompat = "1.7.1"
cardview = "1.0.0"
circleprogress = "1.2.4"
circularimageview = "4.3.1"
constraintlayout = "2.2.1"
coordinatorlayout = "1.3.0"
dotsindicator = "5.1.0"
dotsindicatorVersion = "5.1.0"
drawerlayout = "1.2.0"
exifinterface = "1.4.1"
fillprogresslayout = "0.0.9"
fragmentKtx = "1.8.8"
gradle = "8.11.1"
instadotview = "1.1"
kotlin = "2.2.0"
ktoast = "1.0.3"
library = "1.6.2"
libraryVersion = "2.0.0"
licensesdialog = "2.2.0"
material = "1.12.0"
materialfavoritebutton = "0.1.5"
materialIntro = "1.6"
materialVersion = "1.8.3"
mpandroidchart = "3.1.0.28"
numberslidingpicker = "2cd87266c8e7d7656df9eef964bf062da95833a3"
pagerslidingtabstrip = "1.0.1"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
rx2Timer = "1.0.0"
rxjava = "3.1.11"
ultimateringtonepicker = "3.3.0"
viewpager = "1.1.0"
youtubeplayerCompose = "2024.02.25"
dotsindicatorwithoutviewpager = "1.0.0"
navigationFragmentKtx = "2.9.2"
navigationUiKtx = "2.9.2"


[libraries]
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
circleprogress = { module = "com.github.lzyzsd:circleprogress", version.ref = "circleprogress" }
circularimageview = { module = "com.mikhaellopez:circularimageview", version.ref = "circularimageview" }
#dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicatorVersion" }
fillprogresslayout = { module = "com.github.JDevZone:FillProgressLayout", version.ref = "fillprogresslayout" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
#instadotview = { module = "com.github.hrskrs:InstaDotView", version.ref = "instadotview" }
dotsindicatorwithoutviewpager = { module = "com.github.mazenrashed:DotsIndicatorWithoutViewpager", version.ref = "dotsindicatorwithoutviewpager" }
ktoast = { module = "com.github.onurkagan:ktoast", version.ref = "ktoast" }
library = { module = "com.github.f0ris.sweetalert:library", version.ref = "library" }
licensesdialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesdialog" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-intro = { module = "com.heinrichreimersoftware:material-intro", version.ref = "materialIntro" }
materialfavoritebutton = { module = "com.github.ivbaranov:materialfavoritebutton", version.ref = "materialfavoritebutton" }
mpandroidchart = { module = "com.github.hannesa2:MPAndroidChart", version.ref = "mpandroidchart" }
numberslidingpicker = { module = "com.github.senpl:NumberSlidingPicker", version.ref = "numberslidingpicker" }
pagerslidingtabstrip = { module = "com.astuetz:pagerslidingtabstrip", version.ref = "pagerslidingtabstrip" }
rx2-timer = { module = "com.github.thepacific:rx3-timer", version.ref = "rx2Timer" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
smarttablayout-library = { module = "com.ogaclejapan.smarttablayout:library", version.ref = "libraryVersion" }
ultimateringtonepicker = { module = "com.github.DeweyReed:UltimateRingtonePicker", version.ref = "ultimateringtonepicker" }
utils-v4 = { module = "com.ogaclejapan.smarttablayout:utils-v4", version.ref = "libraryVersion" }
youtubeplayer-compose = { module = "io.github.ilyapavlovskii:youtubeplayer-compose", version.ref = "youtubeplayerCompose" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

