plugins {
    id 'com.android.application'
//    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
//    alias(libs.plugins.kotlin.android)
//    alias(libs.plugins.kotlin.android)
//    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.easyfitness"
    compileSdk = 37

    defaultConfig {
        applicationId "com.fitworkoutfast"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 86
        versionName "0.26.19"
    }

    signingConfigs {
        if (rootProject.file('release.properties').exists()) {
            def props = new Properties()
            props.load(new FileInputStream(rootProject.file('release.properties')))
            release {
                storeFile file(props.keyStore)
                storePassword props.keyStorePassword
                keyAlias props.keyAlias
                keyPassword props.keyAliasPassword
            }
        }
        if (rootProject.file('debug.properties').exists()) {
            def props2 = new Properties()
            props2.load(new FileInputStream(rootProject.file('debug.properties')))
            debug {
                storeFile file(props2.keyStore)
                storePassword props2.keyStorePassword
                keyAlias props2.keyAlias
                keyPassword props2.keyAliasPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            ndk {
                debugSymbolLevel "FULL"
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            if (rootProject.file('release.properties').exists()) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            minifyEnabled false
            resValue("bool", "FIREBASE_CRASH_ENABLED", "false")
            if (rootProject.file('debug.properties').exists()) {
                signingConfig signingConfigs.debug
            }
        }
    }

    compileOptions {
        encoding = 'UTF-8'
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildFeatures {
        viewBinding true
        resValues true
    }

    lint {
        disable 'GoogleAppIndexingWarning'
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
//    kotlinOptions {
//        jvmTarget = '21'
//    }
//    kotlinOptions {
//        jvmTarget = '21'
//    }
//    kotlinOptions {
//        jvmTarget = '21'
//    }
}

configurations.configureEach {
    exclude group: 'com.android.support'
}

dependencies {
    // AndroidX Support
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.activity.compose
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.annotation
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.cardview
    implementation libs.androidx.coordinatorlayout
    implementation libs.androidx.drawerlayout
    implementation libs.androidx.exifinterface
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.recyclerview
    implementation libs.androidx.viewpager

    // UI Components
    implementation libs.material
    implementation libs.androidx.material
    implementation libs.dotsindicator
    implementation libs.dotsindicatorwithoutviewpager
    implementation libs.smarttablayout.library
    implementation libs.utils.v4
    implementation libs.circleprogress
    implementation libs.circularimageview
    implementation libs.material.intro
    implementation libs.materialfavoritebutton
    implementation libs.numberslidingpicker
    implementation libs.fillprogresslayout
    implementation libs.customview

    // Utilities & Other
    implementation libs.library
    implementation libs.mpandroidchart
    implementation libs.licensesdialog
    implementation libs.ktoast
    implementation libs.rxjava
    implementation libs.rx2.timer
    implementation libs.ultimateringtonepicker
    implementation libs.android.image.cropper
    implementation libs.youtubeplayer.compose

    debugImplementation libs.androidx.ui.tooling
}
